name: empty_feature_folder
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.5.0
  shared_preferences: ^2.2.0
  # flutter bloc
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  # google auth
  google_sign_in: ^6.1.4
  # firebase
  firebase_auth: ^4.7.2
  firebase_core: ^2.15.0
  firebase_storage: ^11.0.6
  firebase_database: ^10.2.5
  firebase_analytics: ^10.4.4
  firebase_messaging: ^14.6.5
  #flutter notifications
  flutter_local_notifications: ^15.1.0+1
  flutter_svg: ^2.0.7
  keyboard_dismisser: ^3.0.0
  cloud_firestore: ^4.9.0
  image_picker: ^1.0.2
  firebase_app_check: ^0.1.5+2
  timeago: ^3.5.0
  intl: ^0.18.1




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  assets:
    - assets/images/
    - assets/icons/

  uses-material-design: true


